/**
 * The Northgate Supply vocabulary.
 *
 * Hand-written rather than generated by a faker library: the demo marketplace
 * is desk gear, coffee equipment and audio accessories, and a screenshot of the
 * storefront is a portfolio deliverable (§16). "Ergonomic Walnut Desk Shelf"
 * sells the project; "Handcrafted Granite Chicken" does not. It also keeps the
 * dependency list honest — none of this needs a package.
 */

export type VendorSeed = {
  slug: string;
  displayName: string;
  legalName: string;
  description: string;
  country: string;
  /** Null falls back to PLATFORM_COMMISSION_BPS, which is the common case. */
  commissionBps: number | null;
  /** Drives the §11.5 skewed-tenant scenario: relative share of the catalogue. */
  weight: number;
  categories: readonly string[];
};

/**
 * Eight vendors, with `status` deliberately varied by the seeder rather than
 * fixed here. Weights are uneven on purpose: Harbour Roast and Meridian Audio
 * together carry roughly half the catalogue, which is what makes the cache and
 * load tests meet a realistic hot-tenant distribution instead of a flat one.
 */
export const VENDORS: readonly VendorSeed[] = [
  {
    slug: "harbour-roast",
    displayName: "Harbour Roast Coffee",
    legalName: "Harbour Roast Trading Ltd",
    description:
      "Single-origin beans and the brewing hardware to do them justice. Roasted in small batches on the north dock every Tuesday.",
    country: "GB",
    commissionBps: null,
    weight: 5,
    categories: ["coffee", "brewing-equipment", "grinders"],
  },
  {
    slug: "meridian-audio",
    displayName: "Meridian Audio Supply",
    legalName: "Meridian Audio Supply LLC",
    description:
      "Studio-grade headphones, interfaces and cabling for people who can hear the difference and want the receipts.",
    country: "US",
    commissionBps: null,
    weight: 5,
    categories: ["headphones", "audio-interfaces", "cables"],
  },
  {
    slug: "northgate-desks",
    displayName: "Northgate Desk Works",
    legalName: "Northgate Desk Works Inc",
    description:
      "Sit-stand frames, solid-timber tops and the brackets that hold it all together. Built to outlast the office it sits in.",
    country: "US",
    commissionBps: 1200,
    weight: 4,
    categories: ["desks", "desk-accessories", "storage"],
  },
  {
    slug: "kestrel-keys",
    displayName: "Kestrel Keyboards",
    legalName: "Kestrel Peripherals GmbH",
    description:
      "Mechanical keyboards, switches and keycap sets. Hot-swap everything; solder nothing unless you want to.",
    country: "DE",
    commissionBps: null,
    weight: 4,
    categories: ["keyboards", "keycaps", "desk-accessories"],
  },
  {
    slug: "lumen-lighting",
    displayName: "Lumen Task Lighting",
    legalName: "Lumen Lighting Co",
    description:
      "Monitor bars, desk lamps and colour-accurate panels for rooms that stopped getting daylight hours ago.",
    country: "US",
    commissionBps: null,
    weight: 3,
    categories: ["lighting", "desk-accessories"],
  },
  {
    slug: "atlas-cables",
    displayName: "Atlas Cable Company",
    legalName: "Atlas Cable Company Pty",
    description:
      "USB-C, XLR, patch and power. Braided, shielded, and length-labelled so you stop guessing in the dark.",
    country: "AU",
    commissionBps: 900,
    weight: 3,
    categories: ["cables", "adapters", "desk-accessories"],
  },
  {
    slug: "pinewood-ceramics",
    displayName: "Pinewood Ceramics",
    legalName: "Pinewood Ceramics Studio",
    description:
      "Thrown-by-hand mugs, drippers and servers. Every piece is a little different and that is rather the point.",
    country: "CA",
    commissionBps: null,
    weight: 2,
    categories: ["drinkware", "brewing-equipment"],
  },
  {
    slug: "ironvale-storage",
    displayName: "Ironvale Storage",
    legalName: "Ironvale Storage Solutions",
    description:
      "Powder-coated steel drawers, cable trays and under-desk shelving. Unglamorous, load-rated, honest.",
    country: "GB",
    commissionBps: null,
    weight: 2,
    categories: ["storage", "desk-accessories", "cables"],
  },
] as const;

/**
 * The platform taxonomy (§5.1: vendors choose from it, they do not extend it).
 * Two levels — a handful of roots with children under them — because the PLP in
 * §7.2 has a category rail that needs somewhere to nest.
 */
export const CATEGORY_TREE: readonly {
  slug: string;
  name: string;
  children: readonly { slug: string; name: string }[];
}[] = [
  {
    slug: "coffee",
    name: "Coffee",
    children: [
      { slug: "brewing-equipment", name: "Brewing Equipment" },
      { slug: "grinders", name: "Grinders" },
      { slug: "drinkware", name: "Drinkware" },
    ],
  },
  {
    slug: "audio",
    name: "Audio",
    children: [
      { slug: "headphones", name: "Headphones" },
      { slug: "audio-interfaces", name: "Audio Interfaces" },
    ],
  },
  {
    slug: "workspace",
    name: "Workspace",
    children: [
      { slug: "desks", name: "Desks" },
      { slug: "desk-accessories", name: "Desk Accessories" },
      { slug: "lighting", name: "Lighting" },
      { slug: "storage", name: "Storage" },
    ],
  },
  {
    slug: "peripherals",
    name: "Peripherals",
    children: [
      { slug: "keyboards", name: "Keyboards" },
      { slug: "keycaps", name: "Keycaps" },
      { slug: "cables", name: "Cables" },
      { slug: "adapters", name: "Adapters" },
    ],
  },
] as const;

/** Product name parts, keyed by leaf category slug. */
export const PRODUCT_WORDS: Record<
  string,
  { adjectives: readonly string[]; nouns: readonly string[] }
> = {
  coffee: {
    adjectives: ["Single-Origin", "Washed", "Natural", "Honey-Process", "Dark"],
    nouns: ["Ethiopia Guji", "Colombia Huila", "Kenya Nyeri", "House Blend"],
  },
  "brewing-equipment": {
    adjectives: [
      "Pour-Over",
      "Immersion",
      "Stovetop",
      "Gooseneck",
      "Insulated",
    ],
    nouns: ["Dripper", "Brewer", "Kettle", "Server", "Scale", "Press"],
  },
  grinders: {
    adjectives: ["Conical Burr", "Flat Burr", "Hand", "Electric", "Travel"],
    nouns: ["Grinder", "Mill", "Burr Set"],
  },
  drinkware: {
    adjectives: ["Stoneware", "Double-Walled", "Speckled", "Matte", "Glazed"],
    nouns: ["Mug", "Tumbler", "Cupping Bowl", "Carafe"],
  },
  headphones: {
    adjectives: ["Open-Back", "Closed-Back", "Reference", "Planar", "Studio"],
    nouns: ["Headphones", "Monitors", "IEMs", "Headset"],
  },
  "audio-interfaces": {
    adjectives: ["2-Channel", "4-Channel", "Bus-Powered", "Rackmount"],
    nouns: ["Interface", "Preamp", "Converter", "Mixer"],
  },
  desks: {
    adjectives: ["Sit-Stand", "Solid Walnut", "White Oak", "Compact", "Corner"],
    nouns: ["Desk", "Frame", "Desktop", "Riser"],
  },
  "desk-accessories": {
    adjectives: ["Walnut", "Felt-Lined", "Anodised", "Magnetic", "Low-Profile"],
    nouns: ["Monitor Stand", "Wrist Rest", "Mat", "Tray", "Shelf", "Organiser"],
  },
  lighting: {
    adjectives: ["Colour-Accurate", "Dimmable", "Warm-White", "Clamp-Mount"],
    nouns: ["Monitor Bar", "Desk Lamp", "Panel", "Strip"],
  },
  storage: {
    adjectives: ["Powder-Coated", "Stackable", "Under-Desk", "Lockable"],
    nouns: ["Drawer Unit", "Shelf", "Cable Tray", "Bin", "Cabinet"],
  },
  keyboards: {
    adjectives: ["Hot-Swap", "75%", "65%", "Tenkeyless", "Split"],
    nouns: ["Keyboard", "Barebones Kit", "Numpad"],
  },
  keycaps: {
    adjectives: ["Double-Shot", "Dye-Sub", "Cherry-Profile", "PBT"],
    nouns: ["Keycap Set", "Novelty Kit", "Spacebar"],
  },
  cables: {
    adjectives: ["Braided", "Shielded", "Coiled", "Right-Angle", "Flat"],
    nouns: ["USB-C Cable", "XLR Cable", "Patch Cable", "Power Lead"],
  },
  adapters: {
    adjectives: ["Aluminium", "Compact", "Powered", "Passive"],
    nouns: ["Hub", "Dock", "Adapter", "Splitter"],
  },
};

export const BRANDS: readonly string[] = [
  "Northgate",
  "Kestrel",
  "Meridian",
  "Harbour",
  "Atlas",
  "Lumen",
  "Pinewood",
  "Ironvale",
  "Fieldnote",
  "Compass",
];

/**
 * Option axes, chosen per product to give variants a reason to differ.
 *
 * Every axis carries at least six values on purpose. Variants are drawn with
 * `rng.sample`, which cannot return more elements than the axis holds, so a
 * three-value axis silently caps the catalogue below the 1,500-variant target
 * no matter what the per-product draw asks for.
 */
export const OPTION_AXES: readonly {
  name: string;
  values: readonly string[];
}[] = [
  {
    name: "Colour",
    values: ["Black", "White", "Walnut", "Slate", "Sand", "Forest", "Oxblood"],
  },
  {
    name: "Size",
    values: ["Small", "Medium", "Large", "X-Large", "Compact", "Wide"],
  },
  {
    name: "Length",
    values: ["0.25 m", "0.5 m", "1 m", "2 m", "3 m", "5 m"],
  },
  {
    name: "Weight",
    values: ["125 g", "250 g", "500 g", "750 g", "1 kg", "2 kg"],
  },
  {
    name: "Switch",
    values: [
      "Tactile",
      "Linear",
      "Clicky",
      "Silent Tactile",
      "Silent Linear",
      "Heavy Tactile",
    ],
  },
  {
    name: "Grind",
    values: [
      "Whole Bean",
      "Filter",
      "Espresso",
      "Cafetière",
      "Aeropress",
      "Moka",
    ],
  },
];

export const FIRST_NAMES: readonly string[] = [
  "Amara",
  "Beatrix",
  "Caleb",
  "Dilara",
  "Emeka",
  "Freya",
  "Goran",
  "Hana",
  "Idris",
  "Juno",
  "Kwame",
  "Lena",
  "Mateo",
  "Nadia",
  "Oscar",
  "Priya",
  "Quentin",
  "Rosa",
  "Soren",
  "Tamsin",
  "Ugo",
  "Vera",
  "Wren",
  "Xiomara",
  "Yusuf",
  "Zara",
  "Anders",
  "Bo",
  "Clara",
  "Devika",
  "Elias",
  "Farrah",
];

export const LAST_NAMES: readonly string[] = [
  "Achebe",
  "Bergstrom",
  "Castellanos",
  "Duval",
  "Eriksen",
  "Fontaine",
  "Gallagher",
  "Hovland",
  "Iqbal",
  "Jansen",
  "Kowalski",
  "Lindqvist",
  "Mbeki",
  "Nakamura",
  "Okonkwo",
  "Petrov",
  "Quinn",
  "Rasmussen",
  "Sorensen",
  "Thibault",
  "Ustinov",
  "Villanueva",
  "Whitlock",
  "Yamada",
];

/** Cities paired with their country so addresses are not nonsense. */
export const CITIES: readonly {
  city: string;
  region: string;
  country: string;
  postal: () => string;
}[] = [
  { city: "Portland", region: "OR", country: "US", postal: () => "97201" },
  { city: "Austin", region: "TX", country: "US", postal: () => "78701" },
  { city: "Providence", region: "RI", country: "US", postal: () => "02903" },
  {
    city: "Bristol",
    region: "England",
    country: "GB",
    postal: () => "BS1 4DJ",
  },
  {
    city: "Glasgow",
    region: "Scotland",
    country: "GB",
    postal: () => "G1 3SL",
  },
  { city: "Leipzig", region: "Saxony", country: "DE", postal: () => "04109" },
  { city: "Melbourne", region: "VIC", country: "AU", postal: () => "3000" },
  { city: "Halifax", region: "NS", country: "CA", postal: () => "B3H 2Y9" },
];

export const STREETS: readonly string[] = [
  "Dockside Row",
  "Fenwick Street",
  "Alder Lane",
  "Quarry Road",
  "Bellweather Avenue",
  "Kiln Street",
  "Harbourgate",
  "Mill Yard",
];

export const CARRIERS: readonly string[] = [
  "Royal Mail",
  "UPS",
  "DHL",
  "FedEx",
  "Australia Post",
];
